from langchain_core.tools import tool


# ============================================================
# DATABASE GIẢ
# ============================================================

DISEASES_DB = {
    # Tai Mũi Họng
    "đau họng": {"disease": "Viêm họng", "department": "Tai Mũi Họng"},
    "ho": {"disease": "Viêm họng", "department": "Tai Mũi Họng"},
    "ho khan": {"disease": "Viêm họng", "department": "Tai Mũi Họng"},
    "ho có đờm": {"disease": "Viêm phế quản", "department": "Hô Hấp"},
    "sốt": {"disease": "Cảm cúm", "department": "Nội tổng quát"},
    "sốt cao": {"disease": "Cảm cúm", "department": "Nội tổng quát"},
    "nghẹt mũi": {"disease": "Cảm cúm", "department": "Nội tổng quát"},
    "hắt hơi": {"disease": "Cảm cúm", "department": "Nội tổng quát"},
    "đau tai": {"disease": "Viêm tai giữa", "department": "Tai Mũi Họng"},
    "ù tai": {"disease": "Viêm tai giữa", "department": "Tai Mũi Họng"},
    "chảy nước mũi": {"disease": "Viêm xoang", "department": "Tai Mũi Họng"},
    "đau vùng trán": {"disease": "Viêm xoang", "department": "Tai Mũi Họng"},

    # Tiêu hóa
    "đau bụng": {"disease": "Viêm dạ dày", "department": "Tiêu Hóa"},
    "đau bụng trên": {"disease": "Viêm dạ dày", "department": "Tiêu Hóa"},
    "buồn nôn": {"disease": "Viêm dạ dày", "department": "Tiêu Hóa"},
    "ợ chua": {"disease": "Trào ngược dạ dày", "department": "Tiêu Hóa"},
    "đầy bụng": {"disease": "Trào ngược dạ dày", "department": "Tiêu Hóa"},
    "tiêu chảy": {"disease": "Rối loạn tiêu hóa", "department": "Tiêu Hóa"},
    "táo bón": {"disease": "Rối loạn tiêu hóa", "department": "Tiêu Hóa"},
    "đi ngoài ra máu": {"disease": "Trĩ", "department": "Tiêu Hóa"},

    # Da liễu
    "ngứa da": {"disease": "Viêm da", "department": "Da Liễu"},
    "nổi mẩn": {"disease": "Viêm da", "department": "Da Liễu"},
    "mụn": {"disease": "Mụn nội tiết", "department": "Da Liễu"},
    "mụn nhiều": {"disease": "Mụn nội tiết", "department": "Da Liễu"},
    "rụng tóc": {"disease": "Nấm da đầu", "department": "Da Liễu"},
    "gàu": {"disease": "Nấm da đầu", "department": "Da Liễu"},
    "dị ứng": {"disease": "Dị ứng da", "department": "Da Liễu"},
    "phát ban": {"disease": "Dị ứng da", "department": "Da Liễu"},

    # Tim mạch
    "đau ngực": {"disease": "Tim mạch", "department": "Tim Mạch"},
    "khó thở": {"disease": "Tim mạch", "department": "Tim Mạch"},
    "tim đập nhanh": {"disease": "Rối loạn nhịp tim", "department": "Tim Mạch"},
    "hồi hộp": {"disease": "Rối loạn nhịp tim", "department": "Tim Mạch"},
    "cao huyết áp": {"disease": "Tăng huyết áp", "department": "Tim Mạch"},
    "chóng mặt": {"disease": "Tăng huyết áp", "department": "Tim Mạch"},

    # Thần kinh
    "đau đầu": {"disease": "Migraine", "department": "Thần Kinh"},
    "đau nửa đầu": {"disease": "Migraine", "department": "Thần Kinh"},
    "mất ngủ": {"disease": "Rối loạn giấc ngủ", "department": "Thần Kinh"},
    "ngủ không sâu": {"disease": "Rối loạn giấc ngủ", "department": "Thần Kinh"},
    "tê tay": {"disease": "Thoái hóa đốt sống cổ", "department": "Thần Kinh"},
    "đau cổ": {"disease": "Thoái hóa đốt sống cổ", "department": "Thần Kinh"},

    # Cơ xương khớp
    "đau lưng": {"disease": "Thoái hóa cột sống", "department": "Cơ Xương Khớp"},
    "đau khớp gối": {"disease": "Viêm khớp", "department": "Cơ Xương Khớp"},
    "sưng khớp": {"disease": "Viêm khớp", "department": "Cơ Xương Khớp"},

     # Hô hấp
    "khò khè": {"disease": "Hen phế quản", "department": "Hô Hấp"},
    "tức ngực": {"disease": "Hen phế quản", "department": "Hô Hấp"},
    "thở rít": {"disease": "Hen phế quản", "department": "Hô Hấp"},
    "đau ngực khi ho": {"disease": "Viêm phế quản", "department": "Hô Hấp"},
    "khàn tiếng": {"disease": "Viêm thanh quản", "department": "Tai Mũi Họng"},
    "mất tiếng": {"disease": "Viêm thanh quản", "department": "Tai Mũi Họng"},

    # Tai Mũi Họng
    "đau xoang": {"disease": "Viêm xoang", "department": "Tai Mũi Họng"},
    "ngứa họng": {"disease": "Viêm họng", "department": "Tai Mũi Họng"},
    "đau khi nuốt": {"disease": "Viêm họng", "department": "Tai Mũi Họng"},
    "tai chảy dịch": {"disease": "Viêm tai giữa", "department": "Tai Mũi Họng"},

    # Tiêu hóa
    "đau bụng dưới": {"disease": "Rối loạn tiêu hóa", "department": "Tiêu Hóa"},
    "đau dạ dày": {"disease": "Viêm dạ dày", "department": "Tiêu Hóa"},
    "nóng rát dạ dày": {"disease": "Trào ngược dạ dày", "department": "Tiêu Hóa"},
    "ợ hơi": {"disease": "Trào ngược dạ dày", "department": "Tiêu Hóa"},
    "đi ngoài nhiều lần": {"disease": "Rối loạn tiêu hóa", "department": "Tiêu Hóa"},
    "đầy hơi": {"disease": "Rối loạn tiêu hóa", "department": "Tiêu Hóa"},

     # Da liễu
    "da khô": {"disease": "Viêm da", "department": "Da Liễu"},
    "da đỏ": {"disease": "Viêm da", "department": "Da Liễu"},
    "mụn viêm": {"disease": "Mụn nội tiết", "department": "Da Liễu"},
    "mụn bọc": {"disease": "Mụn nội tiết", "department": "Da Liễu"},
    "rụng tóc nhiều": {"disease": "Nấm da đầu", "department": "Da Liễu"},
    "ngứa da đầu": {"disease": "Nấm da đầu", "department": "Da Liễu"},

    # Tim mạch
    "đau ngực bên trái": {"disease": "Tim mạch", "department": "Tim Mạch"},
    "mệt khi gắng sức": {"disease": "Tim mạch", "department": "Tim Mạch"},
    "khó thở khi nằm": {"disease": "Tim mạch", "department": "Tim Mạch"},
    "đánh trống ngực": {"disease": "Rối loạn nhịp tim", "department": "Tim Mạch"},
    "hoa mắt": {"disease": "Tăng huyết áp", "department": "Tim Mạch"},

    # Thần kinh
    "choáng váng": {"disease": "Migraine", "department": "Thần Kinh"},
    "nhức đầu kéo dài": {"disease": "Migraine", "department": "Thần Kinh"},
    "mỏi cổ": {"disease": "Thoái hóa đốt sống cổ", "department": "Thần Kinh"},
    "tê vai gáy": {"disease": "Thoái hóa đốt sống cổ", "department": "Thần Kinh"},
    "thức giấc giữa đêm": {"disease": "Rối loạn giấc ngủ", "department": "Thần Kinh"},

     # Cơ xương khớp
    "đau vai": {"disease": "Thoái hóa cột sống", "department": "Cơ Xương Khớp"},
    "cứng khớp": {"disease": "Viêm khớp", "department": "Cơ Xương Khớp"},
    "đau khớp cổ tay": {"disease": "Viêm khớp", "department": "Cơ Xương Khớp"},
    "đau thắt lưng": {"disease": "Thoái hóa cột sống", "department": "Cơ Xương Khớp"},

    # Nội tiết
    "khát nước nhiều": {"disease": "Tiểu đường", "department": "Nội Tiết"},
    "tiểu nhiều": {"disease": "Tiểu đường", "department": "Nội Tiết"},
    "sụt cân nhanh": {"disease": "Tiểu đường", "department": "Nội Tiết"},
    "mệt mỏi kéo dài": {"disease": "Suy giáp", "department": "Nội Tiết"},
    "tăng cân bất thường": {"disease": "Suy giáp", "department": "Nội Tiết"},

    # Tiết niệu
    "tiểu buốt": {"disease": "Viêm đường tiết niệu", "department": "Tiết Niệu"},
    "tiểu rắt": {"disease": "Viêm đường tiết niệu", "department": "Tiết Niệu"},
    "đau lưng dưới": {"disease": "Sỏi thận", "department": "Tiết Niệu"},
    "tiểu ra máu": {"disease": "Sỏi thận", "department": "Tiết Niệu"},
}

DOCTORS_DB = {
    "Hen phế quản": [
        {
            "doctor": "Nguyễn Đức H",
            "gender": "Nam",
            "hospital": "Bệnh viện Phổi Trung Ương",
            "hospital_city": "Hà Nội",
            "department": "Hô Hấp",
            "experience": 16,
            "consultation_fee_min": 350000,
            "consultation_fee_max": 600000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "08:00-16:00",
        },
        {
            "doctor": "Trần Thu Y",
            "gender": "Nữ",
            "hospital": "Bệnh viện Đà Nẵng",
            "hospital_city": "Đà Nẵng",
            "department": "Hô Hấp",
            "experience": 9,
            "consultation_fee_min": 220000,
            "consultation_fee_max": 400000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "09:00-17:00",
        },
    ],

     "Viêm thanh quản": [
        {
            "doctor": "Phạm Văn Q",
            "gender": "Nam",
            "hospital": "Bệnh viện Tai Mũi Họng Trung Ương",
            "hospital_city": "Hà Nội",
            "department": "Tai Mũi Họng",
            "experience": 13,
            "consultation_fee_min": 280000,
            "consultation_fee_max": 500000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:30-16:00",
        },
        {
            "doctor": "Lê Thị Z",
            "gender": "Nữ",
            "hospital": "Bệnh viện Chợ Rẫy",
            "hospital_city": "TP.HCM",
            "department": "Tai Mũi Họng",
            "experience": 7,
            "consultation_fee_min": 200000,
            "consultation_fee_max": 350000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:00-15:00",
        },
    ],

     "Tiểu đường": [
        {
            "doctor": "Nguyễn Thị S",
            "gender": "Nữ",
            "hospital": "Bệnh viện Nội Tiết Trung Ương",
            "hospital_city": "Hà Nội",
            "department": "Nội Tiết",
            "experience": 18,
            "consultation_fee_min": 400000,
            "consultation_fee_max": 700000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:00-16:30",
        },
        {
            "doctor": "Hoàng Văn V",
            "gender": "Nam",
            "hospital": "Bệnh viện Đại học Y Dược",
            "hospital_city": "TP.HCM",
            "department": "Nội Tiết",
            "experience": 12,
            "consultation_fee_min": 300000,
            "consultation_fee_max": 550000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:30-15:30",
        },
    ],

     "Suy giáp": [
        {
            "doctor": "Bùi Thanh G",
            "gender": "Nam",
            "hospital": "Bệnh viện Trung Tâm",
            "hospital_city": "Hà Nội",
            "department": "Nội Tiết",
            "experience": 10,
            "consultation_fee_min": 250000,
            "consultation_fee_max": 450000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:30-16:30",
        }
    ],

     "Viêm đường tiết niệu": [
        {
            "doctor": "Đặng Quốc M",
            "gender": "Nam",
            "hospital": "Bệnh viện Việt Đức",
            "hospital_city": "Hà Nội",
            "department": "Tiết Niệu",
            "experience": 15,
            "consultation_fee_min": 350000,
            "consultation_fee_max": 650000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:00-15:00",
        },
        {
            "doctor": "Phan Thị O",
            "gender": "Nữ",
            "hospital": "Bệnh viện Bình Dân",
            "hospital_city": "TP.HCM",
            "department": "Tiết Niệu",
            "experience": 11,
            "consultation_fee_min": 280000,
            "consultation_fee_max": 500000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:00-16:00",
        },
    ],

    "Sỏi thận": [
        {
            "doctor": "Lưu Văn N",
            "gender": "Nam",
            "hospital": "Bệnh viện Việt Đức",
            "hospital_city": "Hà Nội",
            "department": "Tiết Niệu",
            "experience": 20,
            "consultation_fee_min": 500000,
            "consultation_fee_max": 900000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "07:00-14:30",
        }
    ],

    "Viêm họng": [
        {
            "doctor": "Nguyễn Văn A",
            "gender": "Nam",
            "hospital": "Bệnh viện Hà Nội",
            "hospital_city": "Hà Nội",
            "department": "Tai Mũi Họng",
            "experience": 10,
            "consultation_fee_min": 200000,
            "consultation_fee_max": 400000,
            "working_days": [1, 2, 3, 4, 5, 6, 7],
            "time": "08:00-17:00",
        },
        {
            "doctor": "Phạm Thị H",
            "gender": "Nữ",
            "hospital": "Bệnh viện Trung Tâm",
            "hospital_city": "Hà Nội",
            "department": "Tai Mũi Họng",
            "experience": 6,
            "consultation_fee_min": 150000,
            "consultation_fee_max": 300000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "09:00-16:00",
        },
        {
            "doctor": "Đỗ Minh K",
            "gender": "Nam",
            "hospital": "Bệnh viện Đa khoa Miền Bắc",
            "hospital_city": "Hải Phòng",
            "department": "Tai Mũi Họng",
            "experience": 14,
            "consultation_fee_min": 300000,
            "consultation_fee_max": 500000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:30-15:30",
        },
    ],

    "Cảm cúm": [
        {
            "doctor": "Hoàng Văn D",
            "gender": "Nam",
            "hospital": "Bệnh viện Hà Nội",
            "hospital_city": "Hà Nội",
            "department": "Nội tổng quát",
            "experience": 8,
            "consultation_fee_min": 180000,
            "consultation_fee_max": 350000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "08:00-16:00",
        },
        {
            "doctor": "Nguyễn Thị M",
            "gender": "Nữ",
            "hospital": "Bệnh viện Sài Gòn",
            "hospital_city": "TP.HCM",
            "department": "Nội tổng quát",
            "experience": 12,
            "consultation_fee_min": 250000,
            "consultation_fee_max": 450000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "07:30-15:30",
        },
        {
            "doctor": "Lưu Thanh T",
            "gender": "Nam",
            "hospital": "Bệnh viện Đà Nẵng",
            "hospital_city": "Đà Nẵng",
            "department": "Nội tổng quát",
            "experience": 5,
            "consultation_fee_min": 120000,
            "consultation_fee_max": 250000,
            "working_days": [1, 2, 3, 4, 5, 6, 7],
            "time": "10:00-18:00",
        },
    ],

    "Viêm xoang": [
        {
            "doctor": "Bùi Thị X",
            "gender": "Nữ",
            "hospital": "Bệnh viện Tai Mũi Họng Trung Ương",
            "hospital_city": "Hà Nội",
            "department": "Tai Mũi Họng",
            "experience": 11,
            "consultation_fee_min": 250000,
            "consultation_fee_max": 450000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "08:00-16:30",
        },
        {
            "doctor": "Trịnh Văn P",
            "gender": "Nam",
            "hospital": "Bệnh viện Chợ Rẫy",
            "hospital_city": "TP.HCM",
            "department": "Tai Mũi Họng",
            "experience": 18,
            "consultation_fee_min": 400000,
            "consultation_fee_max": 700000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "07:00-15:00",
        },
    ],

    "Viêm dạ dày": [
        {
            "doctor": "Lê Quốc B",
            "gender": "Nam",
            "hospital": "Bệnh viện Trung Tâm",
            "hospital_city": "Hà Nội",
            "department": "Tiêu Hóa",
            "experience": 14,
            "consultation_fee_min": 300000,
            "consultation_fee_max": 600000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "08:00-17:00",
        },
        {
            "doctor": "Mai Thị C",
            "gender": "Nữ",
            "hospital": "Bệnh viện Đà Nẵng",
            "hospital_city": "Đà Nẵng",
            "department": "Tiêu Hóa",
            "experience": 9,
            "consultation_fee_min": 220000,
            "consultation_fee_max": 420000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:30-16:30",
        },
        {
            "doctor": "Nguyễn Hữu E",
            "gender": "Nam",
            "hospital": "Bệnh viện Đại học Y Dược",
            "hospital_city": "TP.HCM",
            "department": "Tiêu Hóa",
            "experience": 20,
            "consultation_fee_min": 500000,
            "consultation_fee_max": 900000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:00-14:00",
        },
    ],

    "Viêm da": [
        {
            "doctor": "Trần Thị B",
            "gender": "Nữ",
            "hospital": "Bệnh viện Hà Nội",
            "hospital_city": "Hà Nội",
            "department": "Da Liễu",
            "experience": 7,
            "consultation_fee_min": 300000,
            "consultation_fee_max": 500000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:00-17:00",
        },
        {
            "doctor": "Đặng Văn K",
            "gender": "Nam",
            "hospital": "Bệnh viện Sài Gòn",
            "hospital_city": "TP.HCM",
            "department": "Da Liễu",
            "experience": 11,
            "consultation_fee_min": 400000,
            "consultation_fee_max": 650000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "08:30-16:30",
        },
        {
            "doctor": "Võ Thị Q",
            "gender": "Nữ",
            "hospital": "Bệnh viện Da Liễu Trung Ương",
            "hospital_city": "Hà Nội",
            "department": "Da Liễu",
            "experience": 16,
            "consultation_fee_min": 450000,
            "consultation_fee_max": 750000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "07:30-15:30",
        },
    ],

    "Tim mạch": [
        {
            "doctor": "Lê Văn C",
            "gender": "Nam",
            "hospital": "Bệnh viện Sài Gòn",
            "hospital_city": "TP.HCM",
            "department": "Tim Mạch",
            "experience": 15,
            "consultation_fee_min": 500000,
            "consultation_fee_max": 800000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:30-15:30",
        },
        {
            "doctor": "Vũ Thị P",
            "gender": "Nữ",
            "hospital": "Bệnh viện Hà Nội",
            "hospital_city": "Hà Nội",
            "department": "Tim Mạch",
            "experience": 13,
            "consultation_fee_min": 450000,
            "consultation_fee_max": 700000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "08:00-16:00",
        },
        {
            "doctor": "Phan Quốc L",
            "gender": "Nam",
            "hospital": "Bệnh viện Huế",
            "hospital_city": "Huế",
            "department": "Tim Mạch",
            "experience": 22,
            "consultation_fee_min": 600000,
            "consultation_fee_max": 1000000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "06:30-14:30",
        },
    ],

    "Migraine": [
        {
            "doctor": "Ngô Văn T",
            "gender": "Nam",
            "hospital": "Bệnh viện Hà Nội",
            "hospital_city": "Hà Nội",
            "department": "Thần Kinh",
            "experience": 9,
            "consultation_fee_min": 300000,
            "consultation_fee_max": 500000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "08:00-15:00",
        },
        {
            "doctor": "Lý Thị R",
            "gender": "Nữ",
            "hospital": "Bệnh viện Trung Tâm",
            "hospital_city": "Hà Nội",
            "department": "Thần Kinh",
            "experience": 8,
            "consultation_fee_min": 250000,
            "consultation_fee_max": 450000,
            "working_days": [1, 2, 3, 4, 5],
            "time": "09:00-17:00",
        },
        {
            "doctor": "Đặng Minh U",
            "gender": "Nam",
            "hospital": "Bệnh viện Chợ Rẫy",
            "hospital_city": "TP.HCM",
            "department": "Thần Kinh",
            "experience": 17,
            "consultation_fee_min": 500000,
            "consultation_fee_max": 850000,
            "working_days": [1, 2, 3, 4, 5, 6],
            "time": "07:00-15:00",
        },
    ],
}

DAY_MAPPING = {
    "thứ 2": 1,
    "thứ 3": 2,
    "thứ 4": 3,
    "thứ 5": 4,
    "thứ 6": 5,
    "thứ 7": 6,
    "chủ nhật": 7,
}


